aws-dbt2-rds appimage, dbt2 v1.5.x
EnterpriseDB/edb-benchmarks pull request #109
Opened 2023-07-25 19:48 UTC by RDiMag

Updates made based on aurora patch to reflect dbt2 v1.5.x and app image changes.

2023-07-25 19:53 UTC, mw2q requested changes
Caught a couple things to fix or double check.

2023-07-25 19:53 UTC, mw2q commented on aws-dbt2-rds/01_deploy/run.sh
> +	-i "${TERRAFORM_PROJECT_PATH}../inventory.yml" \
missing `/` after ${TERRAFORM_PROJECT_PATH}

2023-07-25 19:53 UTC, mw2q commented on aws-dbt2-rds/04_push_results/run.sh
> +RESULTS_DIRECTORY="${SOURCEDIR}/../results"
i don't think this file need any changes..  and SOURCEDIR was removed when it shouldn't have been. :)

2023-07-26 13:26 UTC, bryan-bar requested changes
You have some conflicts due to recently merged in changes: https://github.com/EnterpriseDB/edb-benchmarks/pull/110/commits/39d0f6f75bd65503ba491a959e78f36535dee10b
Please merge in the latest changes from main which will add the validate step and increments all the step directory prefixes.

The inventory template should be moved under `01_provision` once you have the latest changes as it was removed from the `deploy` step.
Here is an example of the template under `01_provision`:
- `inventory.yml.tftpl`: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-biganimal/01_provision/templates/inventory.yml.tftpl
- `generate.yml`: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-biganimal/01_provision/generate.yml
- `run.sh` related changes: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-biganimal/01_provision/run.sh#L9-L13

2023-07-26 13:26 UTC, bryan-bar commented on aws-dbt2-rds/01_deploy/build-inventory.py
This file was removed but the inventory generation was not moved under `00_provision`.

2023-07-26 13:26 UTC, bryan-bar commented on aws-dbt2-rds/01_deploy/templates/inventory.yml.j2
This file was removed but the template file was not moved under `00_provision`.

2023-07-26 15:07 UTC, bryan-bar commented
> You have some conflicts due to recently merged in changes: [39d0f6f](https://github.com/EnterpriseDB/edb-benchmarks/commit/39d0f6f75bd65503ba491a959e78f36535dee10b) Please merge in the latest changes from main which will add the validate step and increments all the step directory prefixes.
> 
> The inventory template should be moved under `01_provision` once you have the latest changes as it was removed from the `deploy` step. Here is an example of the template under `01_provision`:
> 
> * `inventory.yml.tftpl`: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-biganimal/01_provision/templates/inventory.yml.tftpl
> * `generate.yml`: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-biganimal/01_provision/generate.yml
> * `run.sh` related changes: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-biganimal/01_provision/run.sh#L9-L13

Updates to original comment.

Here is an example of the template under 01_provision:

inventory.yml.tftpl: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-biganimal/01_provision/templates/inventory.yml.tftpl
run.sh related changes: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-biganimal/01_provision/run.sh#L20

2023-07-26 18:05 UTC, bryan-bar requested changes

2023-07-26 18:05 UTC, bryan-bar commented on aws-dbt2-rds/01_provision/templates/inventory.yml.tftpl
The file needs to be migrated from jinja to terraform templating.
It will be similar to the one you made for aurora:
https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-aurora/01_provision/templates/inventory.yml.tftpl

2023-07-26 19:27 UTC, RDiMag commented on aws-dbt2-rds/01_provision/templates/inventory.yml.tftpl
Updated!

2023-07-26 20:08 UTC, mw2q approved these changes
Looks good to me.

2023-07-26 20:44 UTC, bryan-bar approved these changes
LGTM

2023-07-26 20:44 UTC, merged