Add manual steps to README
EnterpriseDB/edb-benchmarks pull request #114
Opened 2023-07-27 18:25 UTC by RDiMag

This PR is to update the aws-dbt2-aurora README so that it is useful for people running this benchmark by hand. The Buildbot info has been removed as I understand that would be documented elsewhere.

2023-07-27 19:29 UTC, mw2q requested changes

2023-07-27 19:29 UTC, mw2q commented on aws-dbt2-aurora/README.md
> +Copy your AWS credentials and paste them into the terminal. They can be found in the Command Line or Programmatic Access menu, under Option 1: Set AWS environment variables (Short-term credentials).
i think it's better to say "set the following environment variables" than "paste them into the terminal".

2023-07-27 19:29 UTC, mw2q commented on aws-dbt2-aurora/README.md
> +cd into 01_provision and run the script.
with the recent scripts changes, i think saying "execute 01_provision/run.sh" is better.

2023-07-27 19:29 UTC, mw2q commented on aws-dbt2-aurora/README.md
> +cd into 02_deploy and run the script.
ditto as previous run.sh comment

2023-07-27 19:29 UTC, mw2q commented on aws-dbt2-aurora/README.md
> +cd into 03_prepare and run the script. If desired, adjust parameters as needed before running.
ditto as previous run.sh comment

2023-07-27 19:29 UTC, mw2q commented on aws-dbt2-aurora/README.md
> +cd into 04_execute and run the script.
ditto as previous run.sh comment

2023-07-27 19:29 UTC, mw2q commented on aws-dbt2-aurora/README.md
> +$ export DBT2_WAREHOUSE=1
i think describing the environment.sh file might be better than giving and example like this.  maybe @bryan-bar has an opinion.

2023-07-27 19:44 UTC, RDiMag commented on aws-dbt2-aurora/README.md
> +cd into 01_provision and run the script.
I will fix throughout! Thanks!

2023-07-28 01:58 UTC, bryan-bar commented on aws-dbt2-aurora/README.md
> +$ export DBT2_WAREHOUSE=1
I agree. If we give an example, we might want to do that at the top-level README instead or we might want to create a `docs` directory. The same for credentials, tools, expected execution order and so on. This would help avoid duplicating docs as our benchmarks increase or needing to update them when we do a major change since many follow a similar structure.

Then each benchmark would only describe its intent, any assumptions/limitations and link the benchmark's `README` to the needed files/sections for tools it uses.
** assumption example: most benchmarks use attached storage based on the instance type and we need to make this known since it limits the type of instances that can be used. Preferably, this wouldn't be the case and we would simply add storage for instances we know do not have the needed storage, so we can re-use a single benchmark. AMD Medium benchmark is the only one using additional storage at the moment.

2023-07-28 01:58 UTC, bryan-bar commented on aws-dbt2-aurora/README.md
> +Copy your AWS credentials and paste them into the terminal. They can be found in the Command Line or Programmatic Access menu, under Option 1: Set AWS environment variables (Short-term credentials).
Instead of giving an example, what if we linked back to the official docs since it can vary by account?
This will also be used across the benchmarks so we will want a dedicated section to avoid duplicating docs.

2023-07-28 01:59 UTC, bryan-bar commented on aws-dbt2-aurora/README.md
> +Copy your AWS credentials and paste them into the terminal. They can be found in the Command Line or Programmatic Access menu, under Option 1: Set AWS environment variables (Short-term credentials).
Instead of giving an example, what if we linked back to the official docs since it can vary by account?
This will also be used across the benchmarks so we will want a dedicated section to avoid duplicating docs.

2023-07-28 02:01 UTC, bryan-bar commented on aws-dbt2-aurora/README.md
> +$ export DBT2_WAREHOUSE=1
I agree. If we give an example, we might want to do that at the top-level `README` instead or we might want to create a `docs` directory. The same for credentials, tools, expected execution order and so on. This would help avoid duplicating docs as our benchmarks increase or needing to update them when we do a major change since many follow a similar structure.

Then each benchmark would only describe its intent, any assumptions/limitations and link the benchmark's `README` to the needed files/sections for tools it uses.
** assumption example: most benchmarks use attached storage based on the instance type and we need to make this known since it limits the type of instances that can be used. Preferably, this wouldn't be the case and we would simply add storage for instances we know do not have the needed storage, so we can re-use a single benchmark. AMD Medium benchmark is the only one using additional storage at the moment.

2023-08-04 14:38 UTC, merged