Updates for dbt2 appimage and terraform 1.5.x
EnterpriseDB/edb-benchmarks pull request #116
Opened 2023-08-01 19:27 UTC by RDiMag

These updates were required to get the benchmark to run.

2023-08-01 20:20 UTC, mw2q requested changes

2023-08-01 20:20 UTC, mw2q commented on aws-dbt2-biganimal/03_prepare/playbook-dbt2-build-db.yml
> +        # DBT2PGDATA: /tmp
i believe these can be removed.  did we remove them in the aurora test?

2023-08-01 20:20 UTC, mw2q commented on aws-dbt2-biganimal/04_execute/playbook-dbt2-run.yml
> +        # DRIVER3: "1"
go ahead and delete this line

2023-08-01 20:25 UTC, RDiMag commented on aws-dbt2-biganimal/03_prepare/playbook-dbt2-build-db.yml
> +        # DBT2PGDATA: /tmp
Yes, in aurora we have only PGPASSWORD and PGHOST, while RDS has only PGHOST.
```
    environment:
        PGPASSWORD: "{{ pg_password }}"
        PGHOST: "{{ infra.servers.aurora.postgres.public_ip }}"
```

2023-08-01 22:19 UTC, mw2q commented on aws-dbt2-biganimal/03_prepare/playbook-dbt2-build-db.yml
> +        # DBT2PGDATA: /tmp
interesting.  i was pretty sure we set the password in the .pgpass file, so we don't need to set it here.  do you know how to check the .pgpass file?

2023-08-02 13:08 UTC, RDiMag commented on aws-dbt2-biganimal/03_prepare/playbook-dbt2-build-db.yml
> +        # DBT2PGDATA: /tmp
I haven't found a .pgpass file yet, but there is a dbt2- configure task in Ansible which creates and saves a pg password, so I think you are correct. I don't think we need pg_password here and will remove it.

2023-08-03 22:01 UTC, bryan-bar approved these changes

2023-08-03 22:01 UTC, merged