PER 993 - AWS DBT2 RDS - CW metrics and update pgpass
EnterpriseDB/edb-benchmarks pull request #128
Opened 2023-08-14 16:12 UTC by alfer-edb

14/08/23

- Added region parameter to CW CLI call to correctly gather metrics
- Updated pgpass task to overwrite default entry matching pg_owner
- Added a bypass to GNU Plot task as some graph creation would fail if no datapoints are present. e.g. EBS credits when using provisioned iops.

2023-08-15 03:19 UTC, bryan-bar requested changes

2023-08-15 03:19 UTC, bryan-bar commented on aws-dbt2-rds/04_execute/run.sh
> +	-e "region=${REGION}" \
We can remove this.
`region` will be inside of `environment.yml` and grabbed from the environment. This file is created during `00_validate/run.sh` from [`environment.sh`](https://github.com/alfer-edb/edb-benchmarks/blob/main/aws-dbt2-rds/environment.sh#L10).

2023-08-15 03:19 UTC, bryan-bar commented on roles/get-aws-cloudwatch-rds-postgres-stats/tasks/process-metrics.yml
> +        --region {{ region }}
We might be able to remove this, I see that it is defined below from the terraform outputs.
`--region {{ infra.servers.databases.postgres.region }}`

2023-08-16 11:53 UTC, alfer-edb commented on aws-dbt2-rds/04_execute/run.sh
> +	-e "region=${REGION}" \
Yep, makes sense

2023-08-16 11:54 UTC, alfer-edb commented on roles/get-aws-cloudwatch-rds-postgres-stats/tasks/process-metrics.yml
> +        --region {{ region }}
Okay, so instead of {{ region }} we would need to use {{ infra.servers.databases.postgres.region }}

2023-08-16 15:57 UTC, bryan-bar approved these changes
If we could have this squashed into a single commit otherwise LGTM.

2023-08-16 16:03 UTC, bryan-bar commented on aws-dbt2-rds/02_deploy/playbook-deploy.yml
> +      become: true
Depending on your ide, final newline can be configured.
For VSCode the option is `Insert Final Newline`:
![image](https://github.com/EnterpriseDB/edb-benchmarks/assets/31219516/d37e839e-df81-438d-90d7-5574259e1125)

2023-08-17 18:53 UTC, merged