A series of fixes
EnterpriseDB/edb-benchmarks pull request #149
Opened 2023-09-05 21:51 UTC by mw2q

Fix Aurora log retrieval tasks which exposed a number of other minor fixes and improvements:

* Ignore gnuplot errors that are likely from a lack of meaningful data with some metrics
* Save system logs from driver system
* Fix retrieval of core files when there are not core files to save
* Remove registering of stdout output when the output was not used

2023-09-05 22:05 UTC, dougortiz approved these changes
Looks good

2023-09-06 14:28 UTC, bryan-bar requested changes

2023-09-06 14:28 UTC, bryan-bar commented on aws-dbt2-biganimal/01_provision/templates/infrastructure.yml.j2
> +      spot: true
Do we want to keep this or was this only for testing?
We should remove this or make it a variable to avoid a long test erroring out if max spot price is reached.

2023-09-06 14:29 UTC, mw2q commented on aws-dbt2-biganimal/01_provision/templates/infrastructure.yml.j2
> +      spot: true
that was a mistake, i will remove.

2023-09-06 14:32 UTC, mw2q commented on aws-dbt2-biganimal/01_provision/templates/infrastructure.yml.j2
> +      spot: true
forced push

2023-09-06 14:51 UTC, bryan-bar approved these changes

2023-09-06 14:51 UTC, merged