Role updates
EnterpriseDB/edb-benchmarks pull request #163
Opened 2023-09-19 22:38 UTC by bryan-bar

- `benchmark-steps` role defaults updated
- `provision` tasks added
- `unprovision` tasks added
- Pause for user input during validation step by setting the environment variable `INTERACTIVE=true`
- `.gitignore` updated

Fixes:
- aws-dbt2-biganimal - add `bucket_name`

2023-09-19 22:47 UTC, mw2q requested changes

2023-09-19 22:47 UTC, mw2q commented on .gitignore
> +*results*/
I'm not sure if we need the wildcards around results.  Are things making variations on a results dir?

2023-09-19 22:47 UTC, mw2q commented on aws-edb-postgres-tuner-dbt2/input.yml
> +dbt2_rampup: 45
We want this to stay 15.

2023-09-19 22:47 UTC, mw2q commented on aws-lsr-3-nodes/input.yml
> +tpcc_rampup: 45
I think this was designed for just a 1 min rampup...

2023-09-19 22:47 UTC, mw2q commented on aws-pgd-3-nodes/input.yml
> +dbt2_rampup: 45
This one should stay 1.

2023-09-19 22:47 UTC, mw2q commented on aws-psr-3-nodes/input.yml
> +tpcc_rampup: 45
This one should stay 1.

2023-09-19 22:47 UTC, mw2q commented on aws-tpcc-pgd/input.yml
> +tpcc_rampup: 45
This one should stay 1.

2023-09-19 22:47 UTC, mw2q commented on aws-tpcc-refdata/input.yml
> +tpcc_rampup: 45
This one should stay 1.

2023-09-19 22:47 UTC, mw2q commented on aws-tpcc-tde-medium-amd/input.yml
> +tpcc_rampup: 45
This one should stay 1.

2023-09-19 22:47 UTC, mw2q commented on aws-tpcc-tde/input.yml
> +tpcc_rampup: 45
This one should stay 1.

2023-09-19 22:47 UTC, mw2q commented on aws-tpcc-xdb/input.yml
> +tpcc_rampup: 45
This one should stay 1.

2023-09-19 23:26 UTC, bryan-bar commented on .gitignore
> +*results*/
No variations are being made.
Changed to `results/`

2023-09-19 23:27 UTC, bryan-bar commented on aws-edb-postgres-tuner-dbt2/input.yml
> +dbt2_rampup: 45
rampup commit removed

2023-09-21 00:08 UTC, mw2q approved these changes
this looks sane to me

2023-09-21 18:56 UTC, merged