PER 846: Added ARM Benchmark on AWS Graviton EC2
EnterpriseDB/edb-benchmarks pull request #166
Opened 2023-10-04 09:56 UTC by alfer-edb

Added benchmark for AWS EC2 Graviton

2023-10-05 23:27 UTC, hannahms commented on aws-dbt2-ec2-arm/02_deploy/playbook-deploy.yml
> +    - role: setup_dbt2_driver
iirc, the `setup_repo` role needs to be run on the driver for the epel repo - Mark can confirm this

2023-10-06 10:34 UTC, alfer-edb commented on aws-dbt2-ec2-arm/02_deploy/playbook-deploy.yml
> +    - role: setup_dbt2_driver
I don't see a dependency from EPEL looking at s`etup_dbt2/validate_setup_dbt2.yml `and `setup_dbt2/dbt2_install_packages_driver.yml.` @mw2q  can you confirm?

2023-10-09 11:39 UTC, bryan-bar commented on aws-dbt2-ec2-arm/00_validate/run.sh
> +        -e "terraform_plan_filename=${TERRAFORM_PLAN_FILENAME}"
```suggestion
```suggestion
SOURCEDIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
BENCHMARK_DIRECTORY="$(realpath "${SOURCEDIR}/..")"
ROOT_DIRECTORY="$(realpath "${BENCHMARK_DIRECTORY}/..")"
ANSIBLE_ROLES_PATH="${ROOT_DIRECTORY}/roles"

ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH \
    ansible-playbook "${SOURCEDIR}/run.yml" \
        -e "root_directory=${ROOT_DIRECTORY}" \
        -e "benchmark_directory=${BENCHMARK_DIRECTORY}"
```
```

2023-10-09 11:45 UTC, bryan-bar requested changes

2023-10-09 11:45 UTC, bryan-bar commented on aws-dbt2-ec2-arm/00_validate/run.sh
> +        -e "terraform_plan_filename=${TERRAFORM_PLAN_FILENAME}"
The boilerplate changed a bit. The `benchmark-step` role's validate task will fill out the terraform and results variables based on the root directory and the benchmark directory.
```suggestion
SOURCEDIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
BENCHMARK_DIRECTORY="$(realpath "${SOURCEDIR}/..")"
ROOT_DIRECTORY="$(realpath "${BENCHMARK_DIRECTORY}/..")"
ANSIBLE_ROLES_PATH="${ROOT_DIRECTORY}/roles"

ANSIBLE_ROLES_PATH=$ANSIBLE_ROLES_PATH \
    ansible-playbook "${SOURCEDIR}/run.yml" \
        -e "root_directory=${ROOT_DIRECTORY}" \
        -e "benchmark_directory=${BENCHMARK_DIRECTORY}"
```

2023-10-10 12:17 UTC, alfer-edb commented
Updated `aws-dbt2-ec2-arm/00_validate/run.sh` and added repos for dbt2-driver

2023-10-12 13:49 UTC, alfer-edb commented
Updated edb-ansible https://github.com/EnterpriseDB/edb-ansible/pull/599

2023-10-12 15:48 UTC, bryan-bar approved these changes
LGTM

2023-10-12 15:48 UTC, bryan-bar commented on aws-dbt2-ec2-arm/04_execute/playbook-dbt2-run.yml
> +                          ansible_processor_nproc)) | int }}"
`fpp` equals `0` when `dbt2_connections` is set to a low enough value and rounds down with the `int` filter. This is present in all dbt2 benchmarks and can be fixed in a future patch.

2023-10-12 15:50 UTC, merged