EDB Postgres Tuner test with TPC-C-like workload
EnterpriseDB/edb-benchmarks pull request #30
Opened 2023-01-11 19:26 UTC by mw2q

This benchmark is executed on a AWS EC2 machine (c5.2xlarge).

Environment variables:

- TERRAFORM_PROJECT_PATH - Absolute path to the terraform project created by edb-terraform.
- DBT2_DURATION - Duration in seconds of DBT2 execution.
- DBT2_WAREHOUSE - Number of warehouse.
- DBT2_CONNECTIONS - Number of database connections.
- REPO_USERNAME - Username for EDB public repository
- REPO_PASSWORD - Generated key (not actual password) for EDB public repository
- BENCHMARK_NAME - string used to identify the target folder on the S3 bucket where data points and charts are pushed on.

Note: pandas and matplot Python packages are required

2023-01-20 11:37 UTC, jt-edb requested changes
Please use absolute paths. I know the first caned benchmarks were using relative path, but, using absolute path is way more robust.
Please see this commit: https://github.com/EnterpriseDB/edb-benchmarks/commit/22dc184bfe80c134c93f3004e88cce822d260cbb

2023-01-20 11:37 UTC, jt-edb commented on aws-edb-postgres-tuner-dbt2/README.rst
> +This test is to demonstrated the effectiveness of EDB Postgres Tuner with a
Please use markdown format and file extension.

2023-01-26 02:13 UTC, mw2q commented
Made changes for absolute paths and README format changes.

2023-01-27 13:32 UTC, jt-edb reviewed
LGTM. Only one minor comment.

2023-01-27 13:32 UTC, jt-edb commented on aws-edb-postgres-tuner-dbt2/push_results/run.sh
> +	aws s3 cp ${DIR}/txn/ "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/${DIR}/txn" --recursive
```
mv "${SCRIPT_DIR}/tmp/tuner-off" ${SCRIPT_DIR}/dbt2-data/
mv "${SCRIPT_DIR}/tmp/tuner-measurement" ${SCRIPT_DIR}/dbt2-data/
mv "${SCRIPT_DIR}/tmp/tuner-final" ${SCRIPT_DIR}/dbt2-data/
rm -rf "${SCRIPT_DIR}/tmp"
# Copy infrastructure.yml and vars.yml
cp "${SCRIPT_DIR}/../infrastructure.yml" ${SCRIPT_DIR}/dbt2-data/.
cp "${SCRIPT_DIR}/../vars.yml" ${SCRIPT_DIR}/dbt2-data/.
cd ${SCRIPT_DIR}/dbt2-data
date=$(date +'%Y-%m-%dT%H:%M:%S')

aws s3 cp infrastructure.yml "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/"
aws s3 cp vars.yml "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/"
for DIR in tuner-off tuner-measurement tuner-final; do
	aws s3 cp ${DIR}/readme.txt "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/${DIR}/"
	aws s3 cp ${DIR}/report.html "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/${DIR}/"
	aws s3 cp ${DIR}/db/ "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/${DIR}/db" --recursive
	aws s3 cp ${DIR}/driver/ "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/${DIR}/driver" --recursive
	aws s3 cp ${DIR}/txn/ "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/${DIR}/txn" --recursive
```

2023-02-02 19:54 UTC, bryan-bar commented on aws-edb-postgres-tuner-dbt2/provision/run.sh
> +terraform apply -var-file="${TERRAFORM_PROJECT_PATH}/terraform_vars.json" -auto-approve
This is no longer needed since terraform picks up the variable file automatically.
Either remove it or set to `terraform.tfvars.json`

2023-02-02 19:55 UTC, bryan-bar commented on aws-edb-postgres-tuner-dbt2/unprovision/run.sh
> +terraform destroy -var-file=./terraform_vars.json -auto-approve
`-var-file=` is no longer needed since terraform picks up the variable file automatically and edb-terraform no longer creates `terraform_vars.json`.
Either remove it or set to terraform.tfvars.json

2023-02-02 20:32 UTC, mw2q commented on aws-edb-postgres-tuner-dbt2/push_results/run.sh
> +	aws s3 cp ${DIR}/txn/ "s3://${BUCKET_NAME}/${BENCHMARK_NAME}/${date}/${DIR}/txn" --recursive
Thanks for catching that.  I'll rebase shortly...

2023-02-02 20:33 UTC, mw2q commented on aws-edb-postgres-tuner-dbt2/unprovision/run.sh
> +terraform destroy -var-file=./terraform_vars.json -auto-approve
Ok, I'll remove and rebase shortly.

2023-02-02 20:34 UTC, mw2q commented on aws-edb-postgres-tuner-dbt2/provision/run.sh
> +terraform apply -var-file="${TERRAFORM_PROJECT_PATH}/terraform_vars.json" -auto-approve
Ok, I'll remove and rebase shortly.

2023-02-02 20:42 UTC, mw2q commented
I've updated per comments to date and testing manually while people take time to review again.

2023-02-02 20:47 UTC, mw2q commented
@bryan-bar I'm having some unexpected behavior after upgrading edb-terraform to [92295a0eb14781c0a9d95010a605d1e2d89b930b](https://github.com/EnterpriseDB/edb-terraform/commit/92295a0eb14781c0a9d95010a605d1e2d89b930b)

(```
edb) mark.wong@LIN-USH006L52C % pwd
/home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/provision
(edb) mark.wong@LIN-USH006L52C % time ./run.sh
+++ dirname -- ./run.sh
++ cd -- .
++ pwd
+ SCRIPT_DIR=/home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/provision
+ edb-terraform /home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/project /home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/provision/../infrastructure.yml

    Success!
    You can use now use terraform and see info about your boxes after creation:
    * cd /home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/project
    * terraform apply
    * terraform output -json servers


    servers
./run.sh  0.55s user 0.04s system 99% cpu 0.596 total
```

The `run.sh` script does run `terraform apply -auto-approve`, so I'm not sure I understand what went wrong.

2023-02-02 21:19 UTC, bryan-bar commented
> @bryan-bar I'm having some unexpected behavior after upgrading edb-terraform to [92295a0eb14781c0a9d95010a605d1e2d89b930b](https://github.com/EnterpriseDB/edb-terraform/commit/92295a0eb14781c0a9d95010a605d1e2d89b930b)
> 
> ```
> (edb) mark.wong@LIN-USH006L52C % pwd
> /home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/provision
> (edb) mark.wong@LIN-USH006L52C % time ./run.sh
> +++ dirname -- ./run.sh
> ++ cd -- .
> ++ pwd
> + SCRIPT_DIR=/home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/provision
> + edb-terraform /home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/project /home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/provision/../infrastructure.yml
> 
>     Success!
>     You can use now use terraform and see info about your boxes after creation:
>     * cd /home/mark.wong/src/edb-benchmarks/aws-edb-postgres-tuner-dbt2/project
>     * terraform apply
>     * terraform output -json servers
> 
> 
>     servers
> ./run.sh  0.55s user 0.04s system 99% cpu 0.596 total
> ```
> 
> The `run.sh` script appears to be exiting immediately after running `edb-terraform`. So that says to me that it wasn't successful...

thank you, looking into it.

2023-02-02 23:31 UTC, bryan-bar commented
@mw2q
Thank you for reporting it.
The following PR explains the cause: https://github.com/EnterpriseDB/edb-terraform/pull/27

2023-02-03 01:40 UTC, mw2q commented
I tweaked the vars a bit more in push_results/run.sh some more, and forced a push, but everything works when I run it manually.

2023-02-03 01:41 UTC, mw2q commented on aws-edb-postgres-tuner-dbt2/README.rst
> +This test is to demonstrated the effectiveness of EDB Postgres Tuner with a
Done.

2023-02-03 01:41 UTC, mw2q commented on aws-edb-postgres-tuner-dbt2/README.rst
> +This test is to demonstrated the effectiveness of EDB Postgres Tuner with a
Done.

2023-02-04 01:23 UTC, bryan-bar commented
tested on ebac dev

2023-02-04 01:25 UTC, merged