PER-911 - AWS TPCC PGD 2 Nodes
EnterpriseDB/edb-benchmarks pull request #63
Opened 2023-05-05 22:45 UTC by dougortiz

Benchmark: AWS_TPCC_PGD. Issues fixed:

- TPAExec Install
- Async and Poll in benchmark pipeline
- Terraform PlugIn Cache
- Terraform Path in Workers

2023-05-08 16:26 UTC, bryan-bar commented
http://localhost:8010/#/builders/8/builds/4

2023-05-08 23:45 UTC, bryan-bar requested changes
Build completed.
Thank you for the async fix and validation step.

Please remove the unneeded file and this should be good to go.

2023-05-08 23:45 UTC, bryan-bar commented on aws-tpcc-pgd/deploy/playbook-setup-tpa.yml
> +      become: true
Please remove this file.
```suggestion
```

I do not see this playbook called in `run.sh` and appears to be a duplicate of `playbook-setup-fs.yml`

https://github.com/EnterpriseDB/edb-benchmarks/blob/0251657f7ba89bdfc8f2ce2561ab7ad251759089/aws-tpcc-pgd/deploy/run.sh#L29-L35

2023-05-09 01:01 UTC, dougortiz commented on aws-tpcc-pgd/deploy/playbook-setup-tpa.yml
> +      become: true
Can I remove this in the next PR?

2023-05-09 01:04 UTC, dougortiz commented on aws-tpcc-pgd/deploy/playbook-setup-tpa.yml
> +      become: true
Have already removed it in the PR for AWS TPCC REFDATA

2023-05-09 20:36 UTC, merged