PER-902 - AWS DBT2 RDS
EnterpriseDB/edb-benchmarks pull request #72
Opened 2023-05-23 22:40 UTC by dougortiz

PER-902:
- Added 'README.md'
- Added 'validate' directory
- Added 'run.sh' in validate directory

2023-05-25 23:41 UTC, bryan-bar requested changes

2023-05-25 23:41 UTC, bryan-bar commented on aws-dbt2-rds/validate/run.sh
> +fi
This should be removed as it is not needed by the benchmark.
```suggestion
```

2023-05-25 23:54 UTC, dougortiz commented on aws-dbt2-rds/validate/run.sh
> +fi
Has been removed

2023-05-26 11:50 UTC, bryan-bar requested changes
Please review the comments below:

2023-05-26 11:50 UTC, bryan-bar commented on aws-dbt2-rds/validate/run.sh
> +echo "EDB_BENCHMARK_REPO_BRANCH: $EDB_BENCHMARK_REPO_BRANCH"
This should be removed as well.
```suggestion
```

2023-05-26 11:50 UTC, bryan-bar commented on aws-dbt2-rds/validate/run.sh
> +fi
* Any lowercase variables need to be updated to use UPPERCASE since in some benchmarks both are used.
* `TERRAFORM_PROJECT_PATH` is missing.

I have gone through and exposed the needed variables under each benchmark directory, `<benchmark_name>/environment`, for easy viewing.
If any are missing or need to be updated, please update the environment variable file.

`aws-dbt2-rds` environment file: https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-rds/environment

2023-05-26 11:50 UTC, bryan-bar commented on aws-dbt2-rds/validate/run.sh
In this PR: https://github.com/EnterpriseDB/edb-benchmarks/pull/73 , the directories were renamed with a prefix.
You will need to use `git mv` to rename your directory name to `00_validation` and increment the rest of the directory prefixes, `00_provision` -> `01_provision`.

2023-05-26 22:34 UTC, bryan-bar requested changes

2023-05-26 22:34 UTC, bryan-bar commented on aws-dbt2-rds/00_validate/run.sh
> +TERRAFORM_PROJECT_PATH=
Needed variables are set inside of `environment` for now: 
https://github.com/EnterpriseDB/edb-benchmarks/blob/main/aws-dbt2-rds/environment#L1

`TERRAFORM_PROJECT_PATH` instead needs to be validated for the following:
* Set by the user
* Write access to path
* If the directory exists, we need to give a warning to the user to destroy existing infrastructure. `edb-terraform` fails if the directory exists but we will be able to bypass it later with `--force` or some other option name. Even if `edb-terraform` is not used, we need to be careful of destroying any terraform files so a warning message is needed.

2023-08-22 23:02 UTC, mw2q commented
I think we've covered this with a number of changes since Doug opened this. :)

2023-08-22 23:02 UTC, closed without merging