Per 910 - Validate "aws-tde-pg-upgrade" script in EDB-Benchmark platform
EnterpriseDB/edb-benchmarks pull request #75
Opened 2023-06-01 22:35 UTC by dougortiz

06/01/2023:

- Commented out issues with ansible ‘async’ and ‘poll’
- Fixed key-unwrap-command parameters
- Fixed authentication and execution user account for ‘pg_upgrade’ to execute properly
- Added additional parameters to buildbot interface
  - BENCHMARK_REPO_URL
  - BENCHMARK_REPO_BRANCH
- Fixed issue with TERRAFORM_PLUGIN_CACHE variable
- Added ‘00_validation’ step
- Renamed and renumbered benchmark pipeline steps
- Added ‘[README.md](http://readme.md/)’ file
- Fixed execution ‘pg_upgrade’ execution directory
- Refactored source and target pg_version variables in workflow
- Refactored ‘pg_data’ and ‘pg_wal’ variables for source and target pg_versions
- **Have most benchmark workflow steps working with the exception of the ‘push results’ step because  it is requiring a specific parsing for the output of the upgrade. Paused at this step because was indicated that this step will need team input and refactoring.**

2023-06-02 21:39 UTC, bryan-bar requested changes
Please review the comments below:

2023-06-02 21:39 UTC, bryan-bar commented on run_benchmark.sh
> +        #fi
This following PR changes this to an error message: https://github.com/EnterpriseDB/edb-benchmarks/pull/74

If you could uncomment as it is causing a merge conflict.
```suggestion
        if [[ ! -x "$run_script" ]] && [[ ! $(chmod u+x "$run_script") ]]; then
            echo "Unable to set execution for $run_script" >&2
            exit 1
        fi
```

2023-06-02 21:39 UTC, bryan-bar commented on aws-dbt2-rds/validate/run.sh
duplicate file needs to be removed

2023-06-02 21:39 UTC, bryan-bar commented on aws-dbt2-rds/validate/run.sh
> +fi
Please remove the repo as it is not needed directly by the benchmarks themselves.

2023-06-02 21:39 UTC, bryan-bar commented on aws-tde-pg-upgrade/00_validate/run.sh
> +echo "EDB_BENCHMARK_REPO_BRANCH: $EDB_BENCHMARK_REPO_BRANCH"
Please remove this as it is not needed directly by the benchmarks.

2023-06-02 21:39 UTC, bryan-bar commented on aws-tde-pg-upgrade/00_validate/run.sh
> +fi
Please remove this as it is not needed directly by the benchmarks.

We also need a validation for the repo credential variables:
```shell
EDB_REPO_USERNAME
EDB_REPO_PASSWORD
```

2023-06-02 21:39 UTC, bryan-bar commented on aws-tde-pg-upgrade/05_push_results/run.sh
> +cp -r ${SCRIPT_DIR}/../03_execute/benchmark_data ${SCRIPT_DIR}/report-data
The previous directory index needs to be updated until we have a variable that holds all the results.

```suggestion
cp -r ${SCRIPT_DIR}/../04_execute/benchmark_data ${SCRIPT_DIR}/report-data
```

2023-06-02 21:39 UTC, bryan-bar commented on aws-tde-pg-upgrade/environment
>  EDB_REPO_PASSWORD=
This should be added to the validation.

2023-06-02 21:39 UTC, bryan-bar commented on aws-tde-pg-upgrade/00_validate/run.sh
> +fi
Please update these to use UPPER case.

2023-06-06 12:21 UTC, dougortiz commented on run_benchmark.sh
> +        #fi
Un-commented

2023-06-06 12:21 UTC, dougortiz commented on aws-tde-pg-upgrade/00_validate/run.sh
> +echo "EDB_BENCHMARK_REPO_BRANCH: $EDB_BENCHMARK_REPO_BRANCH"
Removed

2023-06-06 12:21 UTC, dougortiz commented on aws-tde-pg-upgrade/05_push_results/run.sh
> +cp -r ${SCRIPT_DIR}/../03_execute/benchmark_data ${SCRIPT_DIR}/report-data
Updated

2023-06-06 12:22 UTC, dougortiz commented on aws-tde-pg-upgrade/00_validate/run.sh
> +fi
Added to validation

2023-06-06 12:22 UTC, dougortiz commented on aws-tde-pg-upgrade/00_validate/run.sh
> +fi
Updated to UPPER case

2023-08-29 17:27 UTC, closed without merging