Start/end time task added, aws cloudwatch metric task started
EnterpriseDB/edb-benchmarks pull request #77
Opened 2023-06-21 14:38 UTC by RDiMag

Adds start and end time of dbt2-workload task, adds task for aws clodwatch metric-statistics pull (needs work).

2023-06-29 20:08 UTC, mw2q requested changes

2023-06-29 20:08 UTC, mw2q commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +          gnuplot -e "set terminal png size 1000,800; set output '{{ item }}.png'; set xlabel 'Time'; set ylabel 'Average'; set timefmt '%Y-%m-%d, %H:%M'; set xdata time; set bmargin 10; set rmargin
It just occurred to me (or I forgot if you said) does changing timefmt to '%Y-%m-%dT%H:%M' let you now have to use sed?

2023-06-29 20:15 UTC, RDiMag commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +          gnuplot -e "set terminal png size 1000,800; set output '{{ item }}.png'; set xlabel 'Time'; set ylabel 'Average'; set timefmt '%Y-%m-%d, %H:%M'; set xdata time; set bmargin 10; set rmargin
Unfortunately, no... the JSON given doesn't fit nicely with the timefmt options or CSV.

2023-06-29 20:20 UTC, RDiMag commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +          start: {{ start }}
This is leftover from when I was experimenting with pulling start/end times to a txt file. I will remove it since now we are using vars to store start/end times. Thanks!

2023-06-29 20:23 UTC, RDiMag commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +          start: {{ start }}
This actually has been removed since the first commit!

2023-07-03 16:23 UTC, hannahms reviewed
Great work! Just a few comments to take a look at!

2023-07-03 16:23 UTC, hannahms commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +      shell: "date +%Y-%m-%d-%H:%M:%S"
`ansible.builtin.shell`

2023-07-03 16:23 UTC, hannahms commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +      set_fact:
`ansible.builtin.set_fact`

2023-07-03 16:23 UTC, hannahms commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +      shell: "date +%Y-%m-%d-%H:%M:%S"
`ansible.builtin.shell`

2023-07-03 16:23 UTC, hannahms commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +      set_fact:
`ansible.builtin.set_fact`

2023-07-03 16:23 UTC, hannahms commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +      register: result
Remember to add a blank line at the EOF!

2023-07-03 16:23 UTC, hannahms commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +        - WriteThroughput
Can this list be placed into a variable so the variable is looped through instead of having to rewrite these items multiple times?

2023-07-03 20:50 UTC, RDiMag commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +        - WriteThroughput
Yes, I will work on changing this list to a variable.

2023-07-03 20:51 UTC, RDiMag commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +      shell: "date +%Y-%m-%d-%H:%M:%S"
Done!

2023-07-05 16:01 UTC, bryan-bar commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +          --dimensions Name=DBInstanceIdentifier,Value={{ infra.servers.aurora.dbt2.resource_id.0 }}
Is it possible to get the cluster stats instead of per instance? Would it change the `--mertic-name`'s available?

2023-07-05 18:41 UTC, mw2q commented
@bryan-bar & @hannahms : is doing something like having a general vars directory to save the metric variables a good in betweener option to making a new collections?  for example:

have a high level [vars/aws-cloudwatch-rds-postgresql.yml](url) defined the rds postgres variables, and then have individual execution playbooks to import that?

the only other aspect i feel that is a good candidate to abstract is the chart generation with gnuplot.

2023-07-05 19:11 UTC, RDiMag commented on aws-dbt2-aurora/04_execute/playbook-dbt2-run.yml
> +          --dimensions Name=DBInstanceIdentifier,Value={{ infra.servers.aurora.dbt2.resource_id.0 }}
Cluster and Instance metrics mostly overlap and appear to return identical stats when I tested. However, there are some metrics which only return data for Instance, and at least one metric which is only offered for Cluster. We'd need to write a separate task if we want to capture Cluster data, as well.

2023-07-05 22:23 UTC, mw2q commented
huddled with rachel and hannah and hammered out a path for splitting things up.

2023-07-28 20:07 UTC, RDiMag commented
Closing this PR  because the changes were handled and merged in a different PR.

2023-07-28 20:07 UTC, closed without merging