Add PostgreSQL on AWS EC2 with DBT-2 benchmark
EnterpriseDB/edb-benchmarks pull request #78
Opened 2023-06-26 22:27 UTC by mw2q

2023-06-27 14:34 UTC, bryan-bar reviewed
With edb-terraform `v1.5.0`, we can pass in template directories or files (with a `.tftpl` extension), through the cli arguments so they are rendered as part of the terraform lifecycle. 

All comments below are related this. No change is requested and only a suggestion as this was released today (27 June).

2023-06-27 14:34 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/build-inventory.py
With the recent release of edb-terraform `v1.5.0`, we can get rid of this file and build it with terraform templates.

2023-06-27 14:34 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
Here is an example template: https://github.com/EnterpriseDB/edb-terraform/blob/main/infrastructure-examples/v2_inventory.yml.tftpl

The requirement update would be the use of edb-terraform >= `v1.5.0`. All old benchmarks will still be useable as we try to keep updates backwards compatible with 1.0.0 release.

2023-06-27 14:34 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
> +{% endfor %}
```suggestion
%{ for name, values in servers.machines ~}
%{   if values.tags.type == "dbt2-driver" ~}
        ${ name }:
          ansible_host: ${ values.public_ip }
          private_ip: ${ values.private_ip }
          ansible_user: ${ values.operating_system.ssh_user }
          ansible_ssh_private_key_file: ${ values.operating_system.ssh_private_key_file }
%{   endif ~}
%{ endfor ~}
```

2023-06-27 14:34 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
> +{% endfor %}
```suggestion
%{ for name, values in servers.machines ~}
%{   if values.tags.type == "primary" ~}
        ${ name }:
          ansible_host: ${ values.public_ip }
          private_ip: ${ values.private_ip }
          ansible_user: ${ values.operating_system.ssh_user }
          ansible_ssh_private_key_file: ${ values.operating_system.ssh_private_key_file }
%{   endif ~}
%{ endfor ~}
```

2023-06-27 14:34 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/run.sh
> +mv inventory.yml ../.
We could have this removed and instead rely on edb-terraform's modules to handle this during its lifecycle now.

2023-06-27 14:34 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/run.sh
> +	-i ../inventory.yml \
we can then remove the need for these variables as each machine will know its user and ssh key path within the inventory file.

```suggestion
	-i "${TERRAFORM_PROJECT_PATH}/inventory.yml" \
```

2023-06-27 14:36 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
> +{% endfor %}
These assume that we use tags directly instead of the `type`

2023-06-27 15:51 UTC, mw2q commented on aws-dbt2-ec2/01_deploy/build-inventory.py
Ok, I'll remove build-inventory.py.

2023-06-27 15:52 UTC, mw2q commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
Where does v2_inventory.yml.tftpl go? Still in the templates subdirectory?  And I presumed renamed to inventory.yml.tftpl?

2023-06-27 15:53 UTC, mw2q commented on aws-dbt2-ec2/01_deploy/run.sh
> +mv inventory.yml ../.
Ok, I'll removed this this build-inventory.py.

2023-06-27 15:53 UTC, mw2q commented on aws-dbt2-ec2/01_deploy/run.sh
> +	-i ../inventory.yml \
Ok, will remove.

2023-06-27 16:10 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
Yes, so it would be `templates/inventory.yml.tftpl`.
The CLI would need to be updated to use `generate` instead of the old call and pass in the template directory or file (with our terraform modules, we only attempt to render `.tftpl` files and the rest are ignored.)

So the updated command would like something below:
`edb-terraform generate --project-name terraform --work-path ../ --user-templates ../templates --infra-file ../infrastructure.yml`

** `--work-path` will be under $RESULTS soon.

2023-06-27 17:27 UTC, mw2q commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
Ok, updated in subsequent patch.

2023-06-27 17:27 UTC, mw2q commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
> +{% endfor %}
Updated in subsequent patch.

2023-06-27 17:27 UTC, mw2q commented on aws-dbt2-ec2/01_deploy/templates/inventory.yml.j2
> +{% endfor %}
Updated in subsequent patch.

2023-06-27 17:29 UTC, mw2q commented
Pushed new patch with edb-terraform v1.5 updates.

2023-07-07 20:39 UTC, bryan-bar requested changes

2023-07-07 20:39 UTC, bryan-bar commented on aws-dbt2-ec2/03_execute/run.sh
> +	-i ../inventory.yml \
Needs to point to the new `inventory.yml`

2023-07-07 20:39 UTC, bryan-bar commented on aws-dbt2-ec2/02_prepare/run.sh
> +	-i ../inventory.yml \
Needs to point to the new `inventory.yml`

2023-07-08 00:55 UTC, bryan-bar commented on aws-dbt2-ec2/03_execute/run.sh
> +	-vv \
Remove verbosity please

2023-07-08 00:55 UTC, bryan-bar commented on aws-dbt2-ec2/02_prepare/run.sh
> +	-vv \
Remove verbosity please.

2023-07-08 00:56 UTC, bryan-bar commented on aws-dbt2-ec2/01_deploy/run.sh
> +	-vv \
Remove verbosity please

2023-07-11 16:47 UTC, mw2q commented on aws-dbt2-ec2/03_execute/run.sh
> +	-i ../inventory.yml \
Ok, I think I got it.

2023-07-11 16:47 UTC, mw2q commented on aws-dbt2-ec2/03_execute/run.sh
> +	-vv \
Ok.

2023-07-11 16:47 UTC, mw2q commented on aws-dbt2-ec2/01_deploy/run.sh
> +	-vv \
Ok.

2023-07-11 16:48 UTC, mw2q commented
I've made all requested updates and forced push.

2023-07-11 17:01 UTC, bryan-bar approved these changes
LGTM

2023-07-11 17:01 UTC, merged