aws-dbt2-ec2: save all data into RESULTS_DIRECTORY
EnterpriseDB/edb-benchmarks pull request #82
Opened 2023-07-11 21:25 UTC by mw2q

Save terraform information.  Also simplify how test data is archived and saved.

2023-07-11 23:14 UTC, bryan-bar commented on aws-dbt2-ec2/00_provision/run.sh
> +cd "${TERRAFORM_PROJECT_PATH}/${TERRAFORM_PROJECT_NAME}"
Since we usually want the terraform project to be one level above, do we prefer hard coding this in for with the project name?

In this pr, I made updates assuming `terraform` as the project name so we do not need to define it anymore:
https://github.com/EnterpriseDB/edb-benchmarks/pull/84

2023-07-13 18:51 UTC, bryan-bar requested changes
As above, so that we do not need to define the terraform path/name variables, please use these two commits as reference for what should be updated and/or included:
https://github.com/EnterpriseDB/edb-benchmarks/pull/84/commits/90525c9c1ca97a1e332511e6877e7e851511b27a
https://github.com/EnterpriseDB/edb-benchmarks/pull/87/commits/56ace74be72d085c2a5e10e6e2a78956f7f0b6ed

I noticed you used `realpath`, which works with bash under mac right? Do we want to keep it or remove it and expect users to supply full paths?

2023-07-13 19:25 UTC, mw2q commented
> I noticed you used `realpath`, which works with bash under mac right? Do we want to keep it or remove it and expect users to supply full paths?

Yeah, `realpath`  works more consistently for me on macos.  readlink didn't work in certain vm/container corner cases.

2023-07-13 20:47 UTC, mw2q commented on aws-dbt2-ec2/00_provision/run.sh
> +cd "${TERRAFORM_PROJECT_PATH}/${TERRAFORM_PROJECT_NAME}"
ok, hard coded.

2023-07-13 20:48 UTC, mw2q commented
Ok, I think I updated to match the other commits.  Forced pushed.

2023-07-13 20:52 UTC, bryan-bar requested changes

2023-07-13 20:52 UTC, bryan-bar commented on aws-dbt2-ec2/04_push_results/run.sh
> +rm "${RESULTS_DIRECTORY}/dbt2-data.tar.gz"
This should likely be moved within the previous steps playbook so we can move remove this step at a later time.

2023-07-13 20:52 UTC, bryan-bar commented on aws-dbt2-ec2/00_provision/run.sh
> +TERRAFORM_PROJECT_PATH="${RESULTS_DIRECTORY}"
This should be updated to be one directory level above, or another directory besides `results`, so we can exclude needed files from being uploaded.

2023-07-13 21:10 UTC, bryan-bar commented on aws-dbt2-ec2/00_provision/run.sh
> +TERRAFORM_PROJECT_PATH="${RESULTS_DIRECTORY}"
I had removed `TERRAFORM_PROJECT_PATH` to remove the need to define it, but if we should keep it for other types of development, then we can add it back or the use of a default?

2023-07-13 22:35 UTC, mw2q commented on aws-dbt2-ec2/04_push_results/run.sh
> +rm "${RESULTS_DIRECTORY}/dbt2-data.tar.gz"
ok, rebasing

2023-07-13 22:36 UTC, mw2q commented on aws-dbt2-ec2/00_provision/run.sh
> +TERRAFORM_PROJECT_PATH="${RESULTS_DIRECTORY}"
ok, rebasing

2023-07-13 22:36 UTC, mw2q commented
forced push

2023-07-17 18:20 UTC, mw2q commented
I've made another pass at refactoring the terraform and results path to be absolute.

2023-07-17 18:50 UTC, merged