Add role for metrics gathering
EnterpriseDB/edb-benchmarks pull request #92
Opened 2023-07-18 12:45 UTC by RDiMag

Roles directory for tasks associated with getting AWS metric-statistics using the Aurora instance ID.

2023-07-18 16:51 UTC, mw2q commented
Ok.  Let do:
*  get-aws-cloudwatch-aurora-postgres-stats because there is aurora mysql etc
* make main.yml empty because i can't think of anything the role should do just by importing it
* and the other renames as agreed

2023-07-19 20:38 UTC, mw2q requested changes
Looks good.  Just that one EOF that should be a simple fix.

2023-07-19 20:38 UTC, mw2q commented on roles/get-aws-cloudwatch-aurora-postgres-stats/vars/main.yml
> +
I didn't notice this previously.  See if you can find a setting in your editor to always make sure there is always an EOF at the end of the file.

2023-07-20 18:00 UTC, RDiMag commented on roles/get-aws-cloudwatch-aurora-postgres-stats/vars/main.yml
> +
I believe I resolved this.

2023-07-20 20:10 UTC, mw2q requested changes
I think that looks good.  I'm sure you can fix the EOF thing quickly.  Then go ahead and squash this back into a single commit, then I think we can merge it.

2023-07-20 20:10 UTC, mw2q commented on roles/get-aws-cloudwatch-aurora-postgres-stats/tasks/get-end-time.yml
> +
I see one more missing EOF here. :)

2023-07-20 20:55 UTC, merged